### PR TITLE
Synchronize reads/writes to outputData and errorData

### PR DESCRIPTION
**Pull request by harlanhaskins**
Since the FileHandle readabilityHandlers execute asyncronously, possibly
on multiple different queues, we need to guard the reads/writes of the
outputData/errorData on a serial dispatch queue, and block until all
writes have finished.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
This fixes the bug I observed with [Lite](https://github.com/silt-lang/Lite)'s parallel test runner. TSan runs clean with this fix.

**Review by JohnSundell — APPROVED** [review]
Awesome stuff! 👍 Thanks a lot @harlanhaskins 🎉

**Comment by harlanhaskins** [comment]
Thanks for the merge! Mind doing another tag on master so I can update [https://github.com/silt-lang/Lite](Lite)'s `Package.swift`?

**Comment by JohnSundell** [comment]
Sure, will do 👍

**Comment by JohnSundell** [comment]
And it's me who should thank you for contributing ;)

**Comment by JohnSundell** [comment]
Done! https://github.com/JohnSundell/ShellOut/releases/tag/2.1.0

**Pull request merged**
