### PR TITLE
Add Podspec

### PR DESCRIPTION
**Pull request by niklassaers**
Add Podspec so it can be used through CocoaPods. (I'd like to use it as a dependency in a Pod I'm publishing (BoltProtocol, dependency for Theo, the Neo4j driver for Swift))

### CODE REVIEW

**Comment by niklassaers** [comment]
Heh... sorry if that was a bit eager: https://twitter.com/CocoaPodsFeed/status/869985712883552256

**Comment by JohnSundell** [comment]
@niklassaers hehe yeah what's up with that? Did you push this podspec to CocoaPods trunk? 😮

**Comment by niklassaers** [comment]
Yeah, I assumed I didn't have permission, and wanted to see the information provided about who has permission that I get in the error text. Turned out I had permission. Whoops. Sorry about that.

**Comment by JohnSundell** [comment]
@niklassaers No worries, I appreciate the enthusiasm 😉 please transfer the pod to me though 😄 and thanks for adding this podfile 👍

**Review by JohnSundell — APPROVED** [review]

**Comment by niklassaers** [comment]
Thanks. Will do :-)

**Comment by niklassaers** [comment]
Pod should be transferred now :-)

**Pull request merged**
